mattn/anko

builtins/time/time.go
vm/env.go

Not nitpicking, just found these.

Fix some typos.

---

builtins/sort/sort.go
builtins/sort/sort_go18.go
builtins/sort/sort_nongo18.go

fix build for non-go18

---

vm/env_test.go
vm/example_test.go
vm/vm_test.go

Added ExamplePrintHelloWorld
Corrected TestInterruptRaces

Added more TestEnvRaces and updated original

---

vm/vmExpr.go
vm/vm_test.go

convert types of elements to the target of append

---

builtins/core.go

fix keys()

---

builtins/core_test.go
vm/env.go
vm/vm.go
vm/vmExpr.go
vm/vmStmt.go
vm/vm_test.go

Please note this does change how Run output value behavior for let statements when they have multiple values, it will only return the last value set.

 Updated LetsExpr and LetsStmt, added tests

---

builtins/core_test.go
vm/vmArraysAndMaps_test.go
vm/vm_test.go

Added slice tests

---

vm/vmStmt.go
vm/vm_test.go

Added to TestForLoop
Added to TestInterrupts

Added for in map loop

---

vm/vmExprFunction.go

fix address assignment in function arguments

---

vm/vmArraysAndMaps_test.go
vm/vmConvertToX.go
vm/vmExpr.go
vm/vmExprFunction.go
vm/vmReturnsAndFunctions_test.go
vm/vm_test.go

Merge #140

---

parser/parser.go
parser/parser.go.y

syntax error for func(,b){}

---

ast/stmt.go
parser/parser.go
parser/parser.go.y
vm/vm.go
vm/vmArraysAndMaps_test.go
vm/vmExpr.go
vm/vmStmt.go
vm/vm_test.go

add statement for v, ok = m[k]

---

vm/vm_test.go

Hopefully will fix interrupt tests from failing.

Updated TestInterrupts

---

vm/vmExprFunction.go
vm/vmLetExpr.go
vm/vm_test.go

fixes https://github.com/mattn/anko/issues/158
will add tests.

reflect interface

---

ast/astutil/walk.go
ast/astutil/walk_test.go

Merging name change.  Addresses issue #170 in mattn/anko

---

.travis.yml
anko.go
anko_test.go
colortext.go

To make testing much easier, refactoring anko.go. Will have a part 2 after this.

Refactor anko.go part 1

---

anko.go
anko_test.go

Added TestRunInteractive

---

ast/astutil/walk.go
ast/astutil/walk_test.go

add LetMapItemStmt to astutil/walk

---

packages/net.http.go
packages/time.go
vm/example_packages_test.go

Added Duration to time package

Added http example

---

vm/env.go

Add parent interrupt to NewModule

---

ast/stmt.go
vm/vmContainers_test.go
vm/vmConvertToX.go
vm/vmExpr.go
vm/vmExprFunction.go
vm/vmFunctions_test.go
vm/vmStmt.go

Fix convertVMFunctionToType and fix NilCoalescingOpExpr ineffectual assignments

---

ast/stmt.go
vm/vm.go
vm/vmContainers_test.go
vm/vmOperators_test.go
vm/vm_test.go

Removed unneeded reflectValueSliceType

 Improve/cleanup variable tests

---

parser/lexer.go
vm/vm.go
vm/vm_test.go

Fix hex, negative numbers are now LiteralExpr, and updated errors

---

anko.go
ast/ast.go
vm/env.go
vm/vm.go
vm/vmFunctions_test.go
vm/vmStmt.go
vm/vm_test.go

getTypeFromEnv now checks parent scope
ModuleStmt now uses NewModule
Added tests for type scope

0.1.2 - env.NewModule now local. Updated getTypeFromEnv & ModuleStmt

---

anko.go
vm/packages_test.go
vm/vm.go
vm/vmContainers_test.go
vm/vmConvertToX.go
vm/vmExpr.go
vm/vmExprFunction.go
vm/vmFunctions_test.go
vm/vmOperators_test.go

@mattn Please review, merge, and add release

Added recoverFunc & runVMConvertFunction panic VM error

---

anko.go
parser/parser.go
parser/parser.go.y
vm/vmContainers_test.go

@mattn Please review, merge, and create release 0.1.8

Updated parser type_data_struct

---

packages/strconv.go

Add strconv.Atoi

---

parser/parser.go
parser/parser.go.y
vm/vmExprFunction.go
vm/vm_test.go

This fix sets the correct position of lets statements. Without this fix those statements have an empty position (0, 0).

Set position of lets statements
